# Generated by Django 3.2.5 on 2021-07-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
