# Generated by Django 3.2.5 on 2021-07-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0002_alter_consulta_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
