# Generated by Django 3.2.5 on 2021-08-01 02:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('physician_id', models.UUIDField()),
                ('patient_id', models.UUIDField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'consultation',
            },
        ),
        migrations.CreateModel(
            name='PendingPaymentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_id', models.UUIDField(editable=False, unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('tries', models.PositiveIntegerField(default=0)),
                ('processing', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pending_payment',
            },
        ),
    ]
