# Generated by Django 3.2.5 on 2021-07-31 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('physician_id', models.UUIDField()),
                ('patient_id', models.UUIDField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'consultation',
            },
        ),
    ]
