# Generated by Django 3.2.5 on 2021-07-31 17:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('appointment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('tries', models.PositiveIntegerField(default=0)),
                ('processing', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
