# Generated by Django 3.2.5 on 2021-08-01 04:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_id', models.UUIDField(editable=False, unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
